replicaCount: 1

mongo:
  appname: mongo
  image: mongo
  tag: latest
  port: 27017
api:
  appname: api
  image: otomato/maskshop-api
  tag: latest
  port: 80
front:
  appname: front
  image: otomato/maskshop-front
  tag: latest
  port: 80

image:
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
